# Generated by Django 3.1.7 on 2021-04-09 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('Birthdate', models.DateField()),
                ('Passport', models.CharField(max_length=12)),
                ('Phone', models.CharField(max_length=13)),
                ('Email', models.EmailField(max_length=254)),
                ('Login', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('Birthdate', models.DateField()),
                ('Education_certificate', models.PositiveIntegerField()),
                ('Profession', models.CharField(max_length=100)),
                ('Home', models.CharField(max_length=200)),
                ('Login', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Price', models.PositiveIntegerField()),
                ('Description', models.TextField()),
                ('TreinerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.teacher')),
                ('clients', models.ManyToManyField(to='main.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Weekday', models.CharField(max_length=2)),
                ('Time', models.TimeField()),
                ('StyleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.style')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cost', models.IntegerField()),
                ('Payment_date', models.DateField()),
                ('ClientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.client')),
                ('StyleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.style')),
            ],
        ),
    ]
